// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsvhrfnBK7gM9C3jPPsypWHy1fQecfjh4',
    appId: '1:425004809724:web:f461a2de3cb7755e2cc679',
    messagingSenderId: '425004809724',
    projectId: 'drupadity',
    authDomain: 'drupadity.firebaseapp.com',
    storageBucket: 'drupadity.firebasestorage.app',
    measurementId: 'G-78VKP4TDV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzLCt53-su6HdWMV3wjdDcIRaY0uGWiWo',
    appId: '1:425004809724:android:9b6ebccdbf393eb22cc679',
    messagingSenderId: '425004809724',
    projectId: 'drupadity',
    storageBucket: 'drupadity.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKflrDURcXJ9ckLScc6vrle42QeEbcnnQ',
    appId: '1:425004809724:ios:be35486049c286c42cc679',
    messagingSenderId: '425004809724',
    projectId: 'drupadity',
    storageBucket: 'drupadity.firebasestorage.app',
    androidClientId: '425004809724-k2d7vt5n2c4u75v1qun04978j9b739b2.apps.googleusercontent.com',
    iosClientId: '425004809724-52nposa6la4j9o996rlt0dvt06ths5kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKflrDURcXJ9ckLScc6vrle42QeEbcnnQ',
    appId: '1:425004809724:ios:be35486049c286c42cc679',
    messagingSenderId: '425004809724',
    projectId: 'drupadity',
    storageBucket: 'drupadity.firebasestorage.app',
    androidClientId: '425004809724-k2d7vt5n2c4u75v1qun04978j9b739b2.apps.googleusercontent.com',
    iosClientId: '425004809724-52nposa6la4j9o996rlt0dvt06ths5kn.apps.googleusercontent.com',
    iosBundleId: 'com.example.login',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsvhrfnBK7gM9C3jPPsypWHy1fQecfjh4',
    appId: '1:425004809724:web:523f6ec4041792802cc679',
    messagingSenderId: '425004809724',
    projectId: 'drupadity',
    authDomain: 'drupadity.firebaseapp.com',
    storageBucket: 'drupadity.firebasestorage.app',
    measurementId: 'G-T6T06HPH6N',
  );
}
